import { ExecArgs } from "@medusajs/framework/types"
import { ContainerRegistrationKeys } from "@medusajs/framework/utils"
import { SITTER_MODULE } from "../modules/sitter"

const SITTERS = [
  {
    user_id: "seed-camille",
    bio: "Infirmière, deux chats (Mochi et Plume), je garde des chats depuis 6 ans à Paris. Je suis particulièrement à l'aise avec les injections d'insuline, les chats âgés et les routines médicamenteuses complexes.",
    profile_type: "student" as const,
    service_types: ["boarding", "visit", "housesitting"],
    city: "Paris",
    neighborhood: "Charonne",
    arrondissement: "11e",
    is_available: true,
    is_expert: true,
    rating: 4.9,
    review_count: 87,
    price_per_night: 22,
    response_time: "12 min",
    years_experience: 6,
    completed_bookings: 218,
    tags: ["Expert soins", "Chats âgés"],
    color_tint: "#8A9A7B",
  },
  {
    user_id: "seed-mathieu",
    bio: "Illustrateur, je travaille depuis chez moi, ce qui me permet de passer du temps avec les chats dont je m'occupe. Mon chat Oscar me supervise. Spécialité : les chats timides.",
    profile_type: "traveler" as const,
    service_types: ["boarding", "housesitting"],
    city: "Paris",
    neighborhood: "Le Marais",
    arrondissement: "3e",
    is_available: true,
    is_expert: false,
    rating: 4.95,
    review_count: 142,
    price_per_night: 28,
    response_time: "8 min",
    years_experience: 4,
    completed_bookings: 164,
    tags: ["Chats anxieux"],
    color_tint: "#C76F4A",
  },
  {
    user_id: "seed-lea",
    bio: "Étudiante vétérinaire en 4e année. J'ai grandi avec 3 chats, je suis parfaitement à l'aise avec les fratries et les dynamiques entre félins. Visites 2×/jour incluses.",
    profile_type: "student" as const,
    service_types: ["visit", "boarding"],
    city: "Paris",
    neighborhood: "Gros-Caillou",
    arrondissement: "7e",
    is_available: false,
    is_expert: false,
    rating: 4.8,
    review_count: 63,
    price_per_night: 25,
    response_time: "22 min",
    years_experience: 3,
    completed_bookings: 89,
    tags: ["Fratries"],
    color_tint: "#1A1614",
  },
  {
    user_id: "seed-salim",
    bio: "Ancien assistant vétérinaire, je me consacre désormais à la garde de chats. À l'aise avec les chats diabétiques, insuffisants rénaux et traitements complexes.",
    profile_type: "traveler" as const,
    service_types: ["boarding", "visit", "housesitting"],
    city: "Paris",
    neighborhood: "Montmartre",
    arrondissement: "18e",
    is_available: true,
    is_expert: true,
    rating: 4.9,
    review_count: 104,
    price_per_night: 20,
    response_time: "15 min",
    years_experience: 5,
    completed_bookings: 176,
    tags: ["Expert soins"],
    color_tint: "#6E8062",
  },
  {
    user_id: "seed-heloise",
    bio: "Retraitée, ancienne éleveuse de Chartreux. Disponible pour des gardes longues (2+ semaines), présence quasi continue à domicile. Très attentive aux habitudes de chaque chat.",
    profile_type: "traveler" as const,
    service_types: ["boarding", "housesitting"],
    city: "Paris",
    neighborhood: "Saint-Germain",
    arrondissement: "6e",
    is_available: true,
    is_expert: false,
    rating: 5.0,
    review_count: 58,
    price_per_night: 32,
    response_time: "6 min",
    years_experience: 2,
    completed_bookings: 72,
    tags: ["Premium", "Long séjour"],
    color_tint: "#A8583A",
  },
  {
    user_id: "seed-paul",
    bio: "Traducteur, je partage mon appartement avec Nougat et Pépite. Spécialisé dans les foyers multi-chats, je sais répartir attention et jeux sans créer de jalousie.",
    profile_type: "traveler" as const,
    service_types: ["boarding", "visit"],
    city: "Paris",
    neighborhood: "Denfert",
    arrondissement: "14e",
    is_available: true,
    is_expert: false,
    rating: 4.85,
    review_count: 91,
    price_per_night: 23,
    response_time: "18 min",
    years_experience: 4,
    completed_bookings: 131,
    tags: ["Multi-chats"],
    color_tint: "#8A9A7B",
  },
  {
    user_id: "seed-anais",
    bio: "Éducatrice canine reconvertie aux chats. Je suis incollable sur le jeu adapté aux chatons et les stimulations pour chats d'appartement. Vidéos de jeu quotidiennes.",
    profile_type: "student" as const,
    service_types: ["boarding", "visit", "housesitting"],
    city: "Paris",
    neighborhood: "Gambetta",
    arrondissement: "20e",
    is_available: true,
    is_expert: false,
    rating: 4.9,
    review_count: 76,
    price_per_night: 21,
    response_time: "10 min",
    years_experience: 3,
    completed_bookings: 98,
    tags: ["Chatons", "Jeux"],
    color_tint: "#C76F4A",
  },
  {
    user_id: "seed-gabriel",
    bio: "Pharmacien, très rigoureux sur les traitements. J'ai pris soin de ma propre chatte Olympe jusqu'à ses 19 ans. Je connais les spécificités du chat senior sur le bout des doigts.",
    profile_type: "traveler" as const,
    service_types: ["boarding", "visit"],
    city: "Paris",
    neighborhood: "Pigalle",
    arrondissement: "9e",
    is_available: false,
    is_expert: true,
    rating: 4.95,
    review_count: 118,
    price_per_night: 26,
    response_time: "14 min",
    years_experience: 5,
    completed_bookings: 189,
    tags: ["Expert soins", "Chats âgés"],
    color_tint: "#1A1614",
  },
]

export default async function seedSitters({ container }: ExecArgs) {
  const logger = container.resolve(ContainerRegistrationKeys.LOGGER)
  const sitterService = container.resolve(SITTER_MODULE)

  logger.info("Seeding sitters...")

  const existing = await sitterService.listSitters({})
  if (existing.length > 0) {
    logger.info(`${existing.length} sitters déjà en base — seed ignoré.`)
    return
  }

  await sitterService.createSitters(SITTERS)

  logger.info(`✅ ${SITTERS.length} sitters créés avec succès.`)
}
